Microsoft graph powershell hotfix
dfds/ded-toolbox pull request #9
Opened 2021-05-05 23:12 UTC by ZaradarDFDS

2021-05-06 06:18 UTC, avnes commented
I am adding @dfds-pwes as reviewer too. I think he would be better suited to review the Powershell code.

2021-05-06 06:23 UTC, avnes requested changes

2021-05-06 06:23 UTC, avnes commented on microsoft-ubuntu-powershell/README.md
> +./scripts/register_extension_schema.ps1 -AzureADApplicationId 66def2fd-0451-4719-8d00-4a925c746ee2  -ExtensionName "CustomExtension" -ExtensionDataType "string"
This is the AppID of our poc Application Registration. Since ce-toolbox is a public repository I think it would be better to have a non-existing AppID; for instance just all zeros. Then in the documentation also add a note about that the AppID in question is an Application Registration.

2021-05-06 10:13 UTC, ZaradarDFDS commented on microsoft-ubuntu-powershell/README.md
> +./scripts/register_extension_schema.ps1 -AzureADApplicationId 66def2fd-0451-4719-8d00-4a925c746ee2  -ExtensionName "CustomExtension" -ExtensionDataType "string"
As such I think the naming of the param is sufficient to indicate that its an Azure AD application. My goal with this code is not to produce a final release, but rather a MVP that one of the SREs can turn into a proper pwsh module once we have charted a path for creating a container workload that enables us to interface with the AzureAD and MSGraph clis regardless of what OS we use.  :)

2021-05-12 11:39 UTC, avnes approved these changes

2021-05-12 12:10 UTC, dfds-pwes approved these changes
Looks good to me.

2021-05-25 08:38 UTC, merged